edition="2023";

package services.v1;

import "productpb/v1/product.proto";
// import "google/protobuf/go_features.proto";
import "google/api/annotations.proto";
// Necesario para la anotación openapiv2_operation (Swagger)
import "protoc-gen-openapiv2/options/annotations.proto";
import "google/api/field_behavior.proto";
import "google/protobuf/empty.proto";
import "buf/validate/validate.proto";

 option (grpc.gateway.protoc_gen_openapiv2.options.openapiv2_swagger) = {
   info: {
     title: "Echo API";
     version: "1.0";
     description: "";
     contact: {
       name: "gRPC-Gateway && HTTP/json rest project with buf";
       url: "https://github.com/grpc-ecosystem/grpc-gateway";
       email: "none@example.com";
     };
     license: {
       name: "BSD 3-Clause License";
       url: "https://github.com/grpc-ecosystem/grpc-gateway/blob/main/LICENSE";
     };
   };
   schemes: HTTP;
   schemes: HTTPS;
   consumes: "application/json";
   produces: "application/json";
 };

message CreateProductRequest {
    productpb.v1.Product product = 1[(google.api.field_behavior) = REQUIRED];
}

message CreateProductResponse {
    productpb.v1.Product product = 1;
    string msg = 2;
}

message GetProductRequest {
    string product_id = 1[
    (google.api.field_behavior) = REQUIRED,
    (buf.validate.field).cel = {
      id: "product.id.format",
      message: "The provided ID is not a valid MongoDB identifier. It should be a 24-character hexadecimal string (0-9, a-f).",
      expression: "this.matches('^[0-9a-fA-F]{24}$')"
    }];
}

message GetProductResponse {
    productpb.v1.Product product = 1;
}

message GetProductsResponse {
    repeated productpb.v1.Product products = 1;
}

message UpdateProductRequest {
    productpb.v1.Product product = 1[(google.api.field_behavior) = REQUIRED];
}

message UpdateProductResponse {
    productpb.v1.Product product = 1;
    string msg = 2;
}

message DeleteProductRequest {
    string product_id = 1[
    (google.api.field_behavior) = REQUIRED,
    (buf.validate.field).cel = {
      id: "product.id.format",
      message: "The provided ID is not a valid MongoDB identifier. It should be a 24-character hexadecimal string (0-9, a-f).",
      expression: "this.matches('^[0-9a-fA-F]{24}$')"
    }];
}

message DeleteProductResponse {
    string msg = 1;
}

// ProductService es el encargado de gestionar el inventario.
service ProductService {
    // CreateProduct cria um novo produto.
    // Retorna o ID gerado e os detalhes do produto.
    rpc CreateProduct(CreateProductRequest) returns (CreateProductResponse) {
        option (google.api.http) = {
            post: "/productsapi/products"
            body: "*"
        };
    }
  
    // GetProduct obtene um produto por seu ID.
    // Retorna o produto com o ID especificado, o uma mensagem de erro senão é encontrado.
    rpc GetProduct(GetProductRequest) returns (GetProductResponse) {
        option idempotency_level = NO_SIDE_EFFECTS;
        option (google.api.http) = {
            get: "/productsapi/products/{product_id}"
        };
    }
    
    /*
     * GetProducts obtene todos os produtos.
     * Retorna uma lista com todos os produtos existentes.
     */
    rpc GetProducts(google.protobuf.Empty) returns (GetProductsResponse) {
        option idempotency_level = NO_SIDE_EFFECTS;
        option (google.api.http) = {
            get: "/productsapi/products"
        };
    }

    /*
     * UpdateProduct atualiza um produto existente.
     * Retorna o produto atualizado e uma mensagem de sucesso ou erro.
     */
    rpc UpdateProduct(UpdateProductRequest) returns (UpdateProductResponse) {
        option (google.api.http) = {
            put: "/productsapi/products"
            body: "*"
        };
    }

    /*
     * DeleteProduct deleta um produto existente.
     * Retorna uma mensagem de sucesso ou erro.
     */
    rpc DeleteProduct(DeleteProductRequest) returns (DeleteProductResponse) {
        option (google.api.http) = {
            delete: "/productsapi/products/{product_id}"
        };
    }

    /*
     * DeleteProduct deleta um produto existente de Test con Robert.
     * Retorna uma mensagem de sucesso ou erro.
     */
    rpc DeleteProduct2(DeleteProductRequest) returns (DeleteProductResponse) {
        option (google.api.http) = {
            delete: "/productsapi/products_reereererer/{product_id}"
        };
    }
}