// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"

	specui "github.com/oaswrap/spec-ui"
	"github.com/spf13/viper"

	"github.com/oaswrap/spec-ui/config"
	"github.com/oaswrap/spec-ui/rapidoc"
	"github.com/oaswrap/spec-ui/redoc"
	"github.com/oaswrap/spec-ui/scalar"
	"github.com/oaswrap/spec-ui/stoplight"
	"github.com/oaswrap/spec-ui/swaggerui"
)

var (
	DocHandler         *specui.Handler
	TITLE_DOCS         string
	DOC_API_PATH       string
	TYPE_DOCUMENTATION string
)

func loadViper() {
	var err error
	viper.AutomaticEnv()

	logName := viper.GetString("LOGNAME")
	if logName != "" {
		pathDir, _ := os.Getwd()
		viper.AddConfigPath(pathDir)
		viper.SetConfigType("env")
		viper.SetConfigName("app")
		if err = viper.ReadInConfig(); err != nil {
			fmt.Printf("\033[31mError: load app.env in: \033[30m %s, error: %s\n", pathDir, err.Error())
			os.Exit(100)
		}

		viper.SetConfigName("meta_config")
		if err = viper.MergeInConfig(); err != nil {
			fmt.Printf("\033[31mError: load meta_config.env in: \033[30m %s, error: %s\n", pathDir, err.Error())
			os.Exit(100)
		}
	}

	TITLE_DOCS = viper.GetString("TITLE_DOCS")
	DOC_API_PATH = viper.GetString("DOC_API_PATH")
	TYPE_DOCUMENTATION = viper.GetString("TYPE_DOCUMENTATION")
}

func init() {
	loadViper()

	dir, file := filepath.Split(DOC_API_PATH)
	// _ = dir
	// specPath := fmt.Sprintf("/docs/%s", file)
	specPath := filepath.Join("/docs", file)
	assetsPath := filepath.Join("/docs", "assets")

	switch strings.TrimSpace(strings.ToLower(TYPE_DOCUMENTATION)) {
	case "swagger":
		DocHandler = specui.NewHandler(
			specui.WithTitle(TITLE_DOCS),
			specui.WithDocsPath("/docs"),
			specui.WithSpecPath(specPath),
			specui.WithSpecIOFS("docs.swagger.json", os.DirFS(dir)),
			swaggerui.WithUI(
				config.SwaggerUI{
					HideCurl:                 true,
					JsonEditor:               false,
					Layout:                   config.SwaggerLayoutBase,
					DefaultModelsExpandDepth: 1,

					// UIConfig specifies additional SwaggerUIBundle config object properties.
					// See https://swagger.io/docs/open-source-tools/swagger-ui/usage/configuration/ for available options.
					// UIConfig: map[string]string{
					// 	"filter": "true",
					// },
				},
			))
	case "scalar":
		DocHandler = specui.NewHandler(
			specui.WithTitle(TITLE_DOCS),
			specui.WithDocsPath("/docs"),
			specui.WithSpecPath(specPath),
			specui.WithSpecIOFS("docs.swagger.json", os.DirFS(dir)),
			scalar.WithUI(
				config.Scalar{
					// ProxyURL:              "https://proxy.scalar.com", // Set Proxy URL to making API requests
					HideSidebar:           false,
					HideModels:            false,
					DocumentDownloadType:  "json",
					HideTestRequestButton: true,
					HideSearch:            false,
					HideDeveloperTools:    false,
					DarkMode:              false,
					Layout:                "modern",
					Theme:                 "default",
				},
			))
	case "stoplight":
		DocHandler = specui.NewHandler(
			specui.WithTitle(TITLE_DOCS),
			specui.WithDocsPath("/docs"),
			specui.WithSpecPath(specPath),
			specui.WithAssetsPath(assetsPath),
			specui.WithSpecIOFS("docs.swagger.json", os.DirFS(dir)),
			stoplight.WithUI(config.StoplightElements{
				HideExport:     true,
				HideSchemas:    false,
				HideTryIt:      true,
				HideTryItPanel: false,
				Layout:         "responsive",
				// Logo:           "/assets/logo.png",
				Router: "hash",
			}),
		)
	case "redoc":
		DocHandler = specui.NewHandler(
			specui.WithTitle(TITLE_DOCS),
			specui.WithDocsPath("/docs"),
			specui.WithSpecPath(specPath),
			specui.WithSpecIOFS("docs.swagger.json", os.DirFS(dir)),
			redoc.WithUI(config.ReDoc{
				HideSearch:          false, // Hide the search bar.
				HideDownloadButtons: false, // Hides the "Download" button for saving the API definition source file.
				HideSchemaTitles:    true,  // Hide
			}),
		)
	case "rapidoc":
		DocHandler = specui.NewHandler(
			specui.WithTitle(TITLE_DOCS),
			specui.WithDocsPath("/docs"),
			specui.WithSpecPath(specPath),
			specui.WithSpecIOFS("docs.swagger.json", os.DirFS(dir)),
			specui.WithAssetsPath(assetsPath),
			rapidoc.WithUI(config.RapiDoc{
				Theme:       config.RapiDocThemeLight,       // RapiDocTheme,                  // Theme style, "light" or "dark"
				Layout:      config.RapiDocLayoutColumn,     // Layout type, "row" or "column"
				RenderStyle: config.RapiDocRenderStyleRead,  // Render style, "read", "view", or "focused"
				SchemaStyle: config.RapiDocSchemaStyleTable, // Schema style, "table" or "tree"
				// BgColor:            string,             // Background color, e.g. "#fff"
				// TextColor:          string,             // Text color, e.g. "#444"
				// HeaderColor:        string,             // Header color, e.g. "#444444"
				// PrimaryColor:       string,             // Primary color, e.g. "#FF791A"
				HideInfo:           false,              // Hide the info section
				HideHeader:         false,              // Hide the header section
				HideSearch:         true,               // Hide the search bar
				HideAdvancedSearch: false,              // Hide the advanced search bar
				HideTryIt:          true,               // Hide the "Try" feature
				Logo:               "/assets/logo.png", // Logo URL
			}),
		)
	}
}
