# Aqui los container se van a conectar a una red external llamada my_whatsmeow_whatsmeow que es la crfeada por el container de la base datos
# se crea un extra host para los servicios asociado a un nombre de host local  my.host.local 

services:
  # Servicio del proxy en Go
  ${SERVICE_NAME}:
    build:
      context: ./gofiles
      dockerfile: Dockerfile
      args:
        - SERVICE_NAME=${SERVICE_NAME}
        - FOLDER_ALLOWED=${FOLDER_ALLOWED}
        - EXECs=${EXECs}
    container_name: ${SERVICE_NAME}
    ports:
       - "11301:11301"
    volumes:
      - ./gofiles/project_file:/app
    networks:
      - external-network # <--- Usamos el nombre lógico definido abajo
    restart: always

networks:
    external-network: # <--- Nombre lógico para este archivo
        external: true
        name: ${DOCKER_EXTERNAL_NETWORK} # <--- El nombre REAL que ves en 'docker network ls'
   
    # Red criada pode ser criada $ docker network create my_networks_dockers
    #     networks:
    # mongodb_enterprise:
    #     name: nomeservice_my_networks_dockers
    #     driver: bridge