# Aqui los container se van a conectar a una red external llamada my_whatsmeow_whatsmeow que es la crfeada por el container de la base datos
# se crea un extra host para los servicios asociado a un nombre de host local  my.host.local 

services:
  # Servicio del proxy en Go
  $$SERVICE_NAME$$: # <-- service_name
    build:
      context: ./gofiles
      dockerfile: service.dockerfile
    env_file:
      - ./gofiles/project_file/app.env  
    container_name: ${SERVICE_NAME}
    entrypoint: ["sh"]
    command: ["-c", "${MY_CMD}"]
    ports:
       - "${PORT_IN_HOST}:${PORTS}"
    volumes:
      - ./gofiles/project_file:/app
      - ./name_service.conf:/etc/supervisor/conf.d/name_service.conf #(name_service_.conf) nombre del archivo config para el supervisor del servicio
    networks:
      external-network: # <--- Usamos el nombre lógico definido abajo
        ipv4_address: ${IP_CONTAINER}
        # ipv4_address: 192.168.40.10
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: always

networks:
    external-network: # <--- Nombre lógico para este archivo
        external: true
        name: ${DOCKER_EXTERNAL_NETWORK} # <--- El nombre REAL que ves en 'docker network ls', tiene que tener subnet 192.168.40.0/24. ex: docker network create --driver bridge --subnet 192.168.10.0/24 my_red, donde DOCKER_EXTERNAL_NETWORK=my_red 
   
    # Red criada pode ser criada $ docker network create my_networks_dockers
    #     networks:
    # mongodb_enterprise:
    #     name: nomeservice_my_networks_dockers
    #     driver: bridge