[program:<nameservice><port>]
command=/app/Binary/<nameservice><port>
directory=/app/Binary
startretries=100
autorestart=true
stderr_logfile=/var/log/supervisor/<nameservice><port>.err.log
stdout_logfile=/var/log/supervisor/<nameservice><port>.out.log
