[program:<nameservice_APP_NAME_in_app.env><port_PORTS_in_app.env>]
command=/app/cmd/<nameservice_APP_NAME_in_app.env><port_PORTS_in_app.env>
process_name=%(program_name)s_%(process_num)02d
command=/app/cmd/<nameservice_APP_NAME_in_app.env><port_PORTS_in_app.env>
autostart=true
startretries=15
autorestart=true
stopasgroup=true
killasgroup=true
numprocs=1
stderr_logfile=/var/log/supervisor/<nameservice_APP_NAME_in_app.env><port_PORTS_in_app.env>.err.log
stdout_logfile=/var/log/supervisor/<nameservice_APP_NAME_in_app.env><port_PORTS_in_app.env>.out.log
stopwaitsecs=60
stopsignal=sigint
minfds=10240