[program:<nameservice_APP_NAME_in_app.env><port_PORTS_in_app.env>]
command=/app/Binary/<nameservice_APP_NAME_in_app.env><port_PORTS_in_app.env>
directory=/app/Binary
startretries=100
autorestart=true
stderr_logfile=/var/log/supervisor/<nameservice_APP_NAME_in_app.env><port_PORTS_in_app.env>.err.log
stdout_logfile=/var/log/supervisor/<nameservice_APP_NAME_in_app.env><port_PORTS_in_app.env>.out.log
