global:
  scrape_interval: 10s
scrape_configs:
- job_name: app-crud-mongo
  static_configs:
  - targets:
    - my.host.local:1111
- job_name: Services
  static_configs:
  - targets:
    - servicex1.socialhub.pro:13371
    - servicex2.socialhub.pro:13372
    - servicex3.socialhub.pro:13373
    - servicex4.socialhub.pro:13374
    - servicex5.socialhub.pro:13375
    - servicex6.socialhub.pro:13376
    - servicex7.socialhub.pro:13377
    - servicex8.socialhub.pro:13378
    - servicex9.socialhub.pro:13379
    - servicex10.socialhub.pro:13310
    - servicex11.socialhub.pro:13311
    - servicex12.socialhub.pro:13312
    - servicex13.socialhub.pro:13313
    - servicex14.socialhub.pro:13314
    - servicex15.socialhub.pro:13315
    - servicex16.socialhub.pro:13316
    - servicex17.socialhub.pro:13317
    - servicex18.socialhub.pro:13318
    - servicex19.socialhub.pro:13319
    - servicex20.socialhub.pro:13320
    - servicex21.socialhub.pro:13321
    - servicex22.socialhub.pro:13322
    - servicex23.socialhub.pro:13323
    - servicex24.socialhub.pro:13324
    - servicex25.socialhub.pro:13325
    - servicex26.socialhub.pro:13326
    - servicex27.socialhub.pro:13327
    - servicex28.socialhub.pro:13328
    - servicex29.socialhub.pro:13329
    - servicex30.socialhub.pro:13330
    - servicex31.socialhub.pro:13331
    - servicex32.socialhub.pro:13332
    - servicex33.socialhub.pro:13333
    - servicex34.socialhub.pro:13334
    - servicex35.socialhub.pro:13335
    - servicex36.socialhub.pro:13336
    - servicex37.socialhub.pro:13337
    - servicex38.socialhub.pro:13338
    - servicex39.socialhub.pro:13339
    - servicex40.socialhub.pro:13340
    - servicex41.socialhub.pro:13341
    - servicex42.socialhub.pro:13342
    - servicex43.socialhub.pro:13343
    - servicex44.socialhub.pro:13344
    - servicex45.socialhub.pro:13345
    - servicex46.socialhub.pro:13346
    - servicex47.socialhub.pro:13347
    - servicex48.socialhub.pro:13348
    - servicex49.socialhub.pro:13349
    - servicex50.socialhub.pro:13350
    - servicex51.socialhub.pro:13351
    - servicex52.socialhub.pro:13352
    - servicex53.socialhub.pro:13353
    - servicex54.socialhub.pro:13354
    - servicex55.socialhub.pro:13355
    - servicex56.socialhub.pro:13356
    - servicex57.socialhub.pro:13357
    - servicex58.socialhub.pro:13358
    - servicex59.socialhub.pro:13359
    - servicex60.socialhub.pro:13360
    - servicex61.socialhub.pro:13361
    - servicex62.socialhub.pro:13362
    - servicex63.socialhub.pro:13363
    - servicex64.socialhub.pro:13364
    - servicex65.socialhub.pro:13365
    - servicex66.socialhub.pro:13366
    - servicex67.socialhub.pro:13367
    - servicex68.socialhub.pro:13368
    - servicex69.socialhub.pro:13369
    - servicex70.socialhub.pro:13370
