package configs

const (
	TYPE_MESSAGE_TEXT            = 1
	TYPE_MESSAGE_IMAGE           = 2
	TYPE_MESSAGE_AUDIO           = 3
	TYPE_MESSAGE_VIDEO           = 4
	TYPE_MESSAGE_DOCUMENT        = 5
	TYPE_MESSAGE_FORM            = 6
	TYPE_MESSAGE_COMMENTARY      = 7
	TYPE_MESSAGE_CONTACT         = 8
	TYPE_MESSAGE_BUTTON          = 9
	TYPE_MESSAGE_LOCATION        = 10
	TYPE_MESSAGE_REACTION        = 11
	TYPE_MESSAGE_STICKER_AVATAR  = 12
	TYPE_MESSAGE_STICKER_GIF     = 13
	TYPE_MESSAGE_STICKER_STICKER = 14
	TYPE_MESSAGE_CALL_OFFER      = 15
	TYPE_MESSAGE_CALL_TERMINATE  = 16
	TYPE_MESSAGE_PAYMENT         = 17
	TYPE_MESSAGE_URL             = 18
	TYPE_MESSAGE_UNDESCRIBABLE   = 19
)

const (
	LOG_APi    TYPE_LOG_MESSAGE = "API"
	LOG_CONFIG TYPE_LOG_MESSAGE = "CONFIG"
)
