# Esta seccion contiene todas las configuraciones correspondiente al servidor web
[Servidor Web]
Host = 127.0.0.1
Port = 3333
#Tiempos en Segundos
    ;es la duración máxima antes de que se agote el tiempo escribe la respuesta. 
    ;Se reinicia cada vez que aparece un nuevo se lee el encabezado de la solicitud. 
    ;Al igual que ReadTimeout, no permite que los controladores tomen decisiones por 
    ;solicitud. Un valor cero o negativo significa que no habrá tiempo de espera.
WriteTimeout = 25
    ;duración máxima para leer la totalidad solicitud, incluido el cuerpo. 
    ;Un valor cero o negativo significa no habrá tiempo de espera.
ReadTimeout = 10
    ;cantidad máxima de tiempo de espera para la próxima solicitud cuando se habiliten 
    ;los keep-alive. Si se agota el tiempo de inactividad es cero, se utiliza el valor 
    ;de ReadTimeout. si ambos son cero, no hay tiempo de espera.
IdleTimeout = 120

# Esta seccion contiene todas las configuraciones correspondiente al servidor App
[App]
AppID = id_ecs_govel
FolderMigrations=./database/migrations/
# permite que el sistema inicialice la carga de Migrations relacionada con la 
# aplicacion en cuestion archivos /database/migrations/*.sql
# Si es false -> no cargara de forma automatica
# Si es true -> Cargara de forma automatica con la instacncion del objeto que maneja 
# DB
AutoMigration=false
# Permite cargar las migraciones a partir de las definidas en la 
# Carpeta app/models/*.gorm se aplica la definicion y configuracion que se define
# en la Guia de Gorm para crear relaciones y sus Relaciones
# no puede estar true junto con AutoMigration devolvera un error y no
# Cargara migration, el error se visualizara en el archivo de log( logs/serverWeb.log)
# y en la salida estandar. Para que se ejecuten todas las migration 
# Se debe agregar al arreglo Models cada modelo creada de la forma  
# Models = append(Models, &NombreModelo{})
# var Models []interface{} = make([]interface{}, 0) hubicado en init.go 
# en el mismo dentro de la funcion init() se agregaran todas las modelos 1 a 1del
# package "app/model" en caso de no querer cragar las migration de ninguna de estas 
# formas poner AutoMigration y MigrationFromModel a false y implementar tu propio metodo
# de carga de migration si es usando Database que es el apuntador a la 
# instancia gorm global de ecs_govel. 
# Mirar ayuda para configuracion de ActiveOnCascade de db.ini en la descripcion de esta 
# propiedad en la configuracion de base de datos 
MigrationFromModel=false
