# Esta seccion contiene todas las configuraciones correspondiente al servidor web
[Servidor Web]
Host = 127.0.0.1
Port = 3333
#Tiempos en Segundos
    ;es la duración máxima antes de que se agote el tiempo escribe la respuesta. 
    ;Se reinicia cada vez que aparece un nuevo se lee el encabezado de la solicitud. 
    ;Al igual que ReadTimeout, no permite que los controladores tomen decisiones por 
    ;solicitud. Un valor cero o negativo significa que no habrá tiempo de espera.
WriteTimeout = 25
    ;duración máxima para leer la totalidad solicitud, incluido el cuerpo. 
    ;Un valor cero o negativo significa no habrá tiempo de espera.
ReadTimeout = 10
    ;cantidad máxima de tiempo de espera para la próxima solicitud cuando se habiliten 
    ;los keep-alive. Si se agota el tiempo de inactividad es cero, se utiliza el valor 
    ;de ReadTimeout. si ambos son cero, no hay tiempo de espera.
IdleTimeout = 120

# Esta seccion contiene todas las configuraciones correspondiente al servidor App
[App]
AppID = id_ecs_govel
