# Esta seccion contiene todas las configuraciones correspondiente al servidor web
[Servidor Web]
Host = host
Port = 1111

# Esta seccion contiene todas las configuraciones correspondiente al servidor App
[App]
AppID = id_ecs_govel
