[Env DataBase]
UrlEnv ="../.env"
#El archivo .env las variables de base de datos deben llamarse:
    ;DB_HOST     --> Nombre del Host de la base de datos
	;DB_PORT     --> Puerto de la base de datos
	;DB_USER     --> Usuario de la base de datos
	;DB_NAME     --> Nombre de la Base de Datos  
	;DB_PASSWD   --> Contraseña de la base de datos
	;DB_SSL_MODE --> Configuracion de SSL de la base de datos
Driver=mysql