[Env DataBase]
UrlEnv ="../.env"
#El archivo .env las variables de base de datos deben llamarse:
    ;DB_HOST     --> Nombre del Host de la base de datos
	;DB_PORT     --> Puerto de la base de datos
	;DB_USER     --> Usuario de la base de datos
	;DB_NAME     --> Nombre de la Base de Datos  
	;DB_PASSWD   --> Contraseña de la base de datos
	;DB_SSL_MODE --> Configuracion de SSL de la base de datos
Driver=mysql
# Tiempo maximo de conecciones idle en minutos
SetConnMaxLifetime=30
# Cantidad maxima de conexiones idle
SetMaxIdleConns=10
# Cantidad maxima de conexiones abiertas
SetMaxOpenConns=15
# DisableForeignKeyConstraintWhenMigrating: false activa la actualizacion en cascada y la integracion
#referencial y puede dar error al cargar las migrations, cuando migra
# hay que correr (ActiveOnCascade)  con true para que pueda crear todas las tablas y luego con false para agregar actualizacion
# en cascada o ordenar las tablas segun el orden que acomoda para que no de error de 
#integracion referencial si esta a False o sino la otra opcion
# de cargar migration es decir que no sea via gorm sino .sql
# Database.DB, err = gorm.Opens(mysql.Open(ConnStr), &gorm.Config{DisableForeignKeyConstraintWhenMigrating: false})
ActiveOnCascade=false