// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import (
	"io"
	"os"
	"strings"

	c_ "ecs_govel/configs"

	scalargo "github.com/bdpiprava/scalar-go"
	"github.com/swaggo/swag"
)

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {}
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

var (
	ScalarError error
	ScalarHtml  string
)

func init() {
	if c_.DOC_API_PATH != "" {
		file, err := os.OpenFile(c_.DOC_API_PATH, os.O_RDONLY, os.ModePerm)
		if err != nil {
			panic(err)
		}

		by, e := io.ReadAll(file)
		if e != nil {
			panic(e)
		}

		switch strings.ToLower(c_.TYPE_DOCUMENTATION) {
		case "swagger":
			SwaggerInfo.InfoInstanceName = "swagger"
			SwaggerInfo.SwaggerTemplate = string(by)
			swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
		case "scalar":
			ScalarHtml, ScalarError = scalargo.NewV2(
				scalargo.WithSpecBytes(by),
			)

		}
	}
}
