// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import (
	"io"
	"os"

	c_ "ecs_govel/configs"

	"github.com/swaggo/swag"
)

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {}
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	if c_.DOC_API_PATH != "" {
		file, err := os.OpenFile(c_.DOC_API_PATH, os.O_RDONLY, os.ModePerm)
		if err != nil {
			panic(err)
		}

		by, e := io.ReadAll(file)
		if e != nil {
			panic(e)
		}

		SwaggerInfo.InfoInstanceName = "swagger"
		SwaggerInfo.SwaggerTemplate = string(by)
	}

	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
